### ISSUE TITLE
The conversion celsius to fahrenheit is not applied in the uncertainty

### ISSUE THREAD

**Issue by jamarav** [r-quantities/quantities#9]
Hello everybody,

First of all, congratulations for this wonderful package. I have used the units packages the last two years and the possibility to add the uncertainty in the same object is really interesting.

In my first test with this package I have noticed that the conversion celsius/farenhait is correct only for the main measure but incorrect for the uncertainty ( tc = (9/5)*(tf-32) )

This is a simple example to reproduce the error.
```
> library(quantities) 
> temp<-20 
> temp<-set_quantities(temp, unit = 'celsius', errors = 1) 
>  
>  
> temp 
20(1) [°C] 
> temp<-set_units(temp, 'kelvin')
> temp 
293(1) [K]
```
An other error to report is a wrong conversion btu/h to W in uncertainties too. The conversion factor to apply is 1055.056/3600 but applies 1000/3600. Rounding error? I didn't check any other conversion but it would be desirable to check more conversions between imperial/international units.

As commented above, these are my first test with the package and it's possible that I don't use the correct commands.

Thanks in advance

**Comment by Enchufa2** [comment]
Thanks for the report! You are right: it seems that unit conversions involving scaling **and** an offset (such as Celsius to Fahrenheit) are not working properly. Note though that the particular example you used, Celsius to Kelvin, does work properly, because that's just an offset. In other words, a difference of 1 ºC is equal to a difference of 1 K. Therefore, the uncertainty must be the same in that conversion.

**Comment by Enchufa2** [comment]
Fixed now:

```r
x <- set_quantities(20, "°C", 1)
x
#> 20(1) [°C]
set_units(x, "°F")
#> 68(2) [°F]
```

Probably the issue was limited to conversions to/from Fahrenheit, because I can't think right now of any other conversion that involves both a scaling and an offset. Anyway, the new mechanism is much more robust and I believe it covers all cases.

We're in the middle of an update of all packages (units, errors and quantities), so I'll send an update to CRAN with this patch as soon as units and errors are accepted.

The other conversion you mentioned was already ok:

```r
x <- set_quantities(1, "btu/h", 1)
x
#> 1(1) [btu/h]
y <- set_units(x, "W")
y
#> 0.3(3) [W]
```

Note that the uncertainty, provided by the `errors` package, is rounded to one significant digit by default. But internally it's more precise:

```r
errors(x)
#> [1] 1
errors(y)
#> [1] 0.2930711
```

You can modify how many digits you want to show, e.g.:

```r
options(errors.digits=4)
x
#> 1.000(1000) [btu/h]
y
#> 0.2931(2931) [W]
```

And change the notation too:

```r
options(errors.notation="plus-minus")
x
#> 1.000 ± 1.000 [btu/h]
y
#> 0.2931 ± 0.2931 [W]
```
